# Basics of Pytorch: Tensor and Autograd

## Tensor
In the aspect of programming, tensor is a kind of array and support effective computing. Tensor is much like ndarray in nump, but the gpu accerlated computing is supported in tensor in pytorch, please refer to [Tensor.ipynb](https://github.com/chenyuntc/pytorch-book/blob/master/chapter03-tensor_and_autograd/Tensor.ipynb) for detailed guidance.

### Creating Tensor
|     函数	   |           功能          |
|----------------|-------------------------|
|Tensor(*sizes)  |	基础构造函数             |
|tensor(data,)	 |类似np.array的构造函数     |
|ones(*sizes)	 |全1Tensor                |
|zeros(*sizes)	 |全0Tensor                |
|eye(*sizes)	 |对角线为1，其他为0          |
|arange(s,e,step |从s到e，步长为step          |
|linspace(s,e,steps)|	从s到e，均匀切分成steps份 |
|rand/randn(*sizes)	|均匀/标准分布 |
|normal(mean,std)/uniform(from,to) |	正态分布/均匀分布|
|randperm(m)	|随机排列 |

In [5]:
# specify the shape of the tensor
import torch
torch.__version__
a = torch.Tensor(2,3)
a # the value of a is decided by the state of the memory.

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# create tensor by list
b = torch.Tensor([[1,2,3],[4,5,6]])
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [8]:
# convet tensor to list
b.tolist()

[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]

In [9]:
b_size = b.size()
b_size

torch.Size([2, 3])

In [10]:
b.numel() # the amout of elements in b, equal to b.nelement()

6

In [11]:
# create a tensor with the same size of b
c = torch.Tensor(b_size)
# create a tensor with elementd of 2,3
d = torch.Tensor((2,3))
c, d

(tensor([[0., 0., 0.],
         [0., 0., 0.]]), tensor([2., 3.]))

In [12]:
c.shape

torch.Size([2, 3])

In [13]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [14]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [15]:
torch.arange(1,6,2)

tensor([1, 3, 5])

In [16]:
torch.linspace(1,10,3)

tensor([ 1.0000,  5.5000, 10.0000])

In [19]:
#torch.randn(2,3,device=torch.device('cpu'))
torch.randn(2,3,device=torch.device('cuda'))

tensor([[-1.6856, -1.0866,  1.2634],
        [-1.3977,  1.1255, -1.0250]], device='cuda:0')

In [21]:
# randon sequence of length 5
torch.randperm(5)

tensor([3, 1, 2, 4, 0])

In [22]:
# the diagnose of the matrix is 1, the amout of rows and columns are not needed to be equal
torch.eye(2,3,dtype=torch.int)

tensor([[1, 0, 0],
        [0, 1, 0]], dtype=torch.int32)

In [24]:
scalar = torch.tensor(3.1415926)

In [31]:
matrix = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
matrix, matrix.shape
torch.tensor([[0.11111, 0.222222, 0.3333333]],
                     dtype=torch.float64,
                     device=torch.device('cpu'))

tensor([[0.1111, 0.2222, 0.3333]], dtype=torch.float64)

In [32]:
''' we can reshape the tensor by view method, we often add or reduce some dimension, the squeeze and unsqueeze 
function can be used to fuifil the requirements
'''
a = torch.arange(0,6)
a.view(2,3)
b = a.view(-1,3)
b.shape

torch.Size([2, 3])

In [34]:
c=b.unsqueeze(1)
c, c.shape

(tensor([[[0, 1, 2]],
 
         [[3, 4, 5]]]), torch.Size([2, 1, 3]))

In [35]:
b.unsqueeze(-2)

tensor([[[0, 1, 2]],

        [[3, 4, 5]]])

In [50]:
d = b.view(1,1,1,2,3)
d.shape

torch.Size([1, 1, 1, 2, 3])

In [51]:
e= b.view(1,1,1,2,3)
e =e.squeeze(0)
e.shape

torch.Size([1, 1, 2, 3])

In [52]:
f = b.view(1,1,1,2,3)
f = f.squeeze()
f.shape

torch.Size([2, 3])

In [54]:
g = torch.randn(3,4)
g

tensor([[ 0.1214, -1.5941, -0.1733,  1.0814],
        [-0.1090, -0.9253,  1.5381,  1.2909],
        [-0.0798,  0.0968, -1.8025, -2.0932]])

In [55]:
# first row
g[0]

tensor([ 0.1214, -1.5941, -0.1733,  1.0814])

In [56]:
# first column
g[:,0]

tensor([ 0.1214, -0.1090, -0.0798])

In [57]:
# first row, third column element
g[0][2]

tensor(-0.1733)

In [58]:
# first row, last column element
g[0,-1]

tensor(1.0814)

In [59]:
# the first two rows
g[:2]

tensor([[ 0.1214, -1.5941, -0.1733,  1.0814],
        [-0.1090, -0.9253,  1.5381,  1.2909]])

The other select functions of most often used.  

|                             函数	              |           功能    |
|--------------------------------------------------|-------------------|
|index_select(input, dim, index)	               |在指定维度dim上选取，比如选取某些行、某些列|
|masked_select(input, mask)	|例子如上，a[a>0]，使用ByteTensor进行选取|
|non_zero(input)	|非0元素的下标|
|gather(input, dim, index)|	根据index，在dim维度上选取数据，输出的size与index一样|

In [71]:
# [gather解析](https://blog.csdn.net/cpluss/article/details/90260550)
m = torch.Tensor([[1,2],[3,4]])
m
b = torch.gather(m, 1, torch.LongTensor([[0,1],[0,0]]))
b

tensor([[1., 2.],
        [3., 3.]])